[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https: 'unsafe-inline'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"

[[redirects]]
  from = "/robots.txt"
  to = "/static/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/humans.txt"
  to = "/static/humans.txt"
  status = 200
  force = true
